import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                function shouldRedirect() {
                  if (window.location.pathname === '/') return false;
                  var t = Number(sessionStorage.getItem('nav_time') || 0);
                  return Date.now() - t > 3000;
                }
                if (shouldRedirect()) window.location.replace('/');
                window.addEventListener('pageshow', function(e) {
                  if (e.persisted && shouldRedirect()) window.location.replace('/');
                });
                document.addEventListener('visibilitychange', function() {
                  if (document.visibilityState === 'visible' && shouldRedirect()) {
                    window.location.replace('/');
                  }
                });
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
